# This file was generated by GoReleaser. DO NOT EDIT.
cask "th" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e5e820b07eacd3e0cb3f73f8d05e0a019da0c930a6984c66f6699e47005a3237"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c696bd7168d89111a82e624c7ad1c835d451dc843d9cec697e9e0f6e18af62f4"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "th"
  desc "Manage Things 3 tasks from the terminal"
  homepage "https://github.com/totocaster/things-cli-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "th"

  # No zap stanza required

  caveats <<~EOS
    th controls Things 3 through macOS Automation.
    Run `th doctor --check-automation` after install if macOS asks for permission.
  EOS
end
