# This file was generated by GoReleaser. DO NOT EDIT.
cask "th" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "606fc67ee5665605d0b72262071bae0fdc5ca381fba70f70ad39950eb0e9a9ef"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "611419ccc710dc02a29d844ad9aa4a977cd716d31585ee5913a73c40fd25e4cf"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "th"
  desc "Manage Things 3 tasks from the terminal"
  homepage "https://github.com/totocaster/things-cli-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "th"

  # No zap stanza required

  caveats <<~EOS
    th controls Things 3 through macOS Automation.
    Run `th doctor --check-automation` after install if macOS asks for permission.
  EOS
end
