# This file was generated by GoReleaser. DO NOT EDIT.
cask "th" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "12027aed149b0150431210a8879efee0dcc62ba367c88c68da737938af980109"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "314c4849b05c98161c1f48e0581b40d606f9f256d5bbdb6bed8384ab420bce18"
      url "https://github.com/totocaster/things-cli-go/releases/download/v#{version}/th_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "th"
  desc "Manage Things 3 tasks from the terminal"
  homepage "https://github.com/totocaster/things-cli-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "th"

  # No zap stanza required

  caveats <<~EOS
    th reads Things data locally and uses macOS Automation for mutations.
    Run `th doctor --check-automation` if macOS asks for Things automation permission.
  EOS
end
