# typed: false
# frozen_string_literal: true

# This file is generated by totocaster/refmode's release workflow.
class Refmode < Formula
  desc "List and switch Apple display reference modes"
  homepage "https://github.com/totocaster/refmode"
  url "https://github.com/totocaster/refmode/releases/download/v1.0.0/refmode-1.0.0-aarch64-apple-darwin.tar.gz"
  sha256 "d6ce2cd0cdf3a939238fe6b3a01808a3e18ce8a5d7f94a429488a1d33dabd1f7"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :ventura

  def install
    bin.install "bin/refmode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/refmode --version")
    assert_match "refmode", shell_output("#{bin}/refmode --help")
  end
end
