# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A simple Go CLI tool for generating note filenames based on date/time"
  homepage "https://github.com/totocaster/stamp"
  version "0.3.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/stamp/releases/download/v0.3.0/stamp_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "c48695c281a7f7479feb311ad08d6871f8fc12368e1c24443be9e45b60ff27c2"

      def install
        bin.install "stamp"
        # Create nid symlink
        bin.install_symlink "stamp" => "nid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/stamp/releases/download/v0.3.0/stamp_0.3.0_Darwin_arm64.tar.gz"
      sha256 "063fec6305c03e3a2e241fd2da224ddd50775407f133303546cefe2151d11f37"

      def install
        bin.install "stamp"
        # Create nid symlink
        bin.install_symlink "stamp" => "nid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/stamp/releases/download/v0.3.0/stamp_0.3.0_Linux_x86_64.tar.gz"
      sha256 "7ece20f79b9281e3510f9a4f8389d7aef986a7edc628d6274a8e26e0004ae409"
      def install
        bin.install "stamp"
        # Create nid symlink
        bin.install_symlink "stamp" => "nid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/stamp/releases/download/v0.3.0/stamp_0.3.0_Linux_arm64.tar.gz"
      sha256 "d146e509db81fb1f91f4ae35412821c2eb6956af059a1d21c408b4a2e0c3da92"
      def install
        bin.install "stamp"
        # Create nid symlink
        bin.install_symlink "stamp" => "nid"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/stamp version")
    assert_match(/\d{4}-\d{2}-\d{2}/, shell_output("#{bin}/stamp daily"))
    assert_predicate bin/"nid", :exist?
    assert_match(/\d{4}-\d{2}-\d{2}/, shell_output("#{bin}/nid daily"))
  end
end
