# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTasks < Formula
  desc "Companion CLI for the Vault Tasks Obsidian plugin"
  homepage "https://github.com/totocaster/vault-tasks-obsidian-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/vault-tasks-obsidian-cli/releases/download/v0.1.0/vault-tasks_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b3aa7ca7086b2c2dbccbf95685d489cd992d1ddb5f4204ceab034df296b5bd63"

      define_method(:install) do
        bin.install "vault-tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/vault-tasks-obsidian-cli/releases/download/v0.1.0/vault-tasks_0.1.0_Darwin_arm64.tar.gz"
      sha256 "942ea2d106e48a30234971ba413657a43c0f3b09a1c29316a3fbd222c9312628"

      define_method(:install) do
        bin.install "vault-tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/vault-tasks-obsidian-cli/releases/download/v0.1.0/vault-tasks_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c62d055b729cfd78965feb44e7eafab65575b1b7062d8ddd5901f94daf2e0f0b"
      define_method(:install) do
        bin.install "vault-tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/vault-tasks-obsidian-cli/releases/download/v0.1.0/vault-tasks_0.1.0_Linux_arm64.tar.gz"
      sha256 "be0acfa11f46f9e06e31991b3efe7c26888e17d872a5187dc99556bb6358fb66"
      define_method(:install) do
        bin.install "vault-tasks"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vault-tasks --version")
    assert_match "sections", shell_output("#{bin}/vault-tasks --help")
  end
end
