# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whoopy < Formula
  desc "Unofficial WHOOP data CLI written in Go"
  homepage "https://github.com/totocaster/whoopy"
  version "0.3.6"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/whoopy/releases/download/v0.3.6/whoopy_0.3.6_Darwin_x86_64.tar.gz"
      sha256 "5075bb07fe77eda5953f58b5762576bb01e5f26d1895cb00cc9027cdc7fe310e"

      define_method(:install) do
        bin.install "whoopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/whoopy/releases/download/v0.3.6/whoopy_0.3.6_Darwin_arm64.tar.gz"
      sha256 "584243785ce35c83a7639413abd18c80d7945f81ce2a6dc15087798b725a842e"

      define_method(:install) do
        bin.install "whoopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/whoopy/releases/download/v0.3.6/whoopy_0.3.6_Linux_x86_64.tar.gz"
      sha256 "631502a1af8505273606621bc25ab373b790cae919a4c2c3c39c030ae518edbe"
      define_method(:install) do
        bin.install "whoopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/whoopy/releases/download/v0.3.6/whoopy_0.3.6_Linux_arm64.tar.gz"
      sha256 "d54eeac8c9f72d904d84d40daa80b196319f562c81a1bda9ef3bbf1bf854526c"
      define_method(:install) do
        bin.install "whoopy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whoopy --version")
    assert_match "profile", shell_output("#{bin}/whoopy --help")
  end
end
