# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whoopy < Formula
  desc "Official WHOOP data CLI in Go"
  homepage "https://github.com/totocaster/whoopy"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/whoopy/releases/download/v0.1.0/whoopy_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "288f098a295071ad7a487f0f2ecaf49e56f0d7e1af2abda47014b79584883e40"

      define_method(:install) do
        bin.install "whoopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/whoopy/releases/download/v0.1.0/whoopy_0.1.0_Darwin_arm64.tar.gz"
      sha256 "09c9ceaa924c067c04a2d5136d2c988a4994cdaa73f7382ed13ab1fe94e6a9df"

      define_method(:install) do
        bin.install "whoopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/whoopy/releases/download/v0.1.0/whoopy_0.1.0_Linux_x86_64.tar.gz"
      sha256 "3409a8b26721ad435acd1d3438b38c6e0380ee5e8dadfe1842dea206579d2f6b"
      define_method(:install) do
        bin.install "whoopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/whoopy/releases/download/v0.1.0/whoopy_0.1.0_Linux_arm64.tar.gz"
      sha256 "b16a4d1d702ce23967b218bfe8ed4e8475c4e17ac6de8967032197a6688fa3b6"
      define_method(:install) do
        bin.install "whoopy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whoopy --version")
    assert_match "whoopy profile", shell_output("#{bin}/whoopy --help")
  end
end
