# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Withingy < Formula
  desc "Unofficial Withings data CLI written in Go"
  homepage "https://github.com/totocaster/withingy"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/withingy/releases/download/v0.3.0/withingy_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "a28f3a59d5e2a1df952afff1cea22d49023f06d7334f658f9580a3aa8766dbf0"

      define_method(:install) do
        bin.install "withingy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/withingy/releases/download/v0.3.0/withingy_0.3.0_Darwin_arm64.tar.gz"
      sha256 "cd65f185e84cb1ca88523dc2c19a8fab54c0829d2d41426085bea05122b52d7e"

      define_method(:install) do
        bin.install "withingy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/withingy/releases/download/v0.3.0/withingy_0.3.0_Linux_x86_64.tar.gz"
      sha256 "78f601c079b0091d583b17f52f5b5583d8076ea51c1af824fe591814beb7051b"
      define_method(:install) do
        bin.install "withingy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/withingy/releases/download/v0.3.0/withingy_0.3.0_Linux_arm64.tar.gz"
      sha256 "5d146852d0a128ba17f3096347a55b30a32548e5ac6cec27e78effc027aeb1fe"
      define_method(:install) do
        bin.install "withingy"
      end
    end
  end

  test do
    assert_match "withingy", shell_output("#{bin}/withingy --version")
    assert_match "activity", shell_output("#{bin}/withingy --help")
  end
end
