# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Withingy < Formula
  desc "Unofficial Withings data CLI written in Go"
  homepage "https://github.com/totocaster/withingy"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/totocaster/withingy/releases/download/v0.4.1/withingy_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "b3b6bc90387218743df7e029d6421daeab3528dc787daa2ed7ae4907e98e5fe1"

      define_method(:install) do
        bin.install "withingy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/totocaster/withingy/releases/download/v0.4.1/withingy_0.4.1_Darwin_arm64.tar.gz"
      sha256 "7588bbd47b2b2bb528646f2834b63640fe9f35e5ecf706aad2e9ce81cbcd164d"

      define_method(:install) do
        bin.install "withingy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/withingy/releases/download/v0.4.1/withingy_0.4.1_Linux_x86_64.tar.gz"
      sha256 "3d67483e87b8961ab390c0658fa708f42c80644f5d9a2125a6e00038d4d2cd10"
      define_method(:install) do
        bin.install "withingy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/totocaster/withingy/releases/download/v0.4.1/withingy_0.4.1_Linux_arm64.tar.gz"
      sha256 "525762857ca31a106bb777ea56a7a3f90c3684f1cbbbf1937e2073992cc062b9"
      define_method(:install) do
        bin.install "withingy"
      end
    end
  end

  test do
    assert_match "withingy", shell_output("#{bin}/withingy --version")
    assert_match "activity", shell_output("#{bin}/withingy --help")
  end
end
